--- 
knit: "bookdown::render_book"
title: "ICE Marketing (Blocks 5 & 6)"
site: bookdown::bookdown_site
bibliography: [book.bib]
csl: american-marketing-association.csl
link-citations: yes
documentclass: book
---

# Course Summary {-}

Welcome to the Marketing component of Fall ICE! 

This website includes outlines for the four group presentations you can choose
from, an outline for your midterm project, and a daily schedule for our class
sessions.

During our time together, we will focus and expand on the marketing discipline's
first law:

> “Don't sell what you happen to make; make what the consumer wants to buy”
[@fennell-1978, p. 38]. 

Our class sessions will hone your ability to apply critical thinking skills to
the managerial decisions being asked of marketers in today's information-based
economy. Oftentimes these decisions pertain to how a company should go about
designing its marketing mix, which is composed of the **famous** 4 Ps (product,
price, promotion, and place).

Conceptualizing marketing as the act of generating, disseminating, and
responding to market intelligence [@kohli-jaworski-1990] will allow us to
discuss how marketing can be practiced organization-wide to help companies
attain a market orientation and optimize their triple bottom lines for profits,
people, and the planet [@elkington-2018].

If asked the question "what is marketing?" during our first class session, you
might define marketing similar to how you would define advertising. In contrast,
by the time our last class session hits on `r class_session[[16, "date"]]`, you
should find that your view of marketing has broadened and deepened, no matter
your starting point. Indeed, marketing is a shared responsibility and everyone
in an organization needs to perform the role of marketing on a continuous basis,
whether they "sit" in the marketing department or not. The reason being is that
learning is at the core of the marketing process, so everything employees do to
"embrace reality and deal with it" [@dalio-2017, p. 132] falls into the realm of
marketing.